### ISSUE TITLE
Inter-chromsome contacts

### ISSUE THREAD

**Issue by yancychy** [js2264/HiCExperiment#12]
Hi, can HiCExperiment import the contacts between different chormsomes? Thank you.

``` R
hicObj <-  HiCExperiment::import( f3, format = 'hic', focus = "arm_2L|arm_2R")
print(hicObj)

Error:
Error in char2coords(coords) : Cannot coerce the provided string into a Pairs object
```

**Comment by js2264** [comment]
Your import fails because the `import` function does not support inferring the length of chromosome whose names contain a `_`. To bypass this limitation, you can manually specify the `focus = "arm_2L:1-100000|arm_2R:1-1000000"` (or whatever `end` you want, eg the arm length). Feel free to reopen if this does not solve your issue.

**Comment by yancychy** [comment]
Thanks. It works.
